-- USA LA BASE DE DATOS
USE CadenaRestauracion;

-- DESHABILITA LAS FOREIGN KEY'S
SET FOREIGN_KEY_CHECKS = 0; 

-- LIMPIA LOS REGISTROS DE CADA TABLA
TRUNCATE TABLE REGISTRAR;
TRUNCATE TABLE TRABAJO;
TRUNCATE TABLE INCIDENCIA;
TRUNCATE TABLE ATENDER;
TRUNCATE TABLE COCINAR;
TRUNCATE TABLE POSEER;
TRUNCATE TABLE LIMPIAR;
TRUNCATE TABLE PROVEER;
TRUNCATE TABLE USAR;
TRUNCATE TABLE TELEFONO;
TRUNCATE TABLE CLIENTE_FIDELIZADO;
TRUNCATE TABLE PEDIDO;
TRUNCATE TABLE TRABAJADOR;
TRUNCATE TABLE ENCARGADO;
TRUNCATE TABLE CAJERO;
TRUNCATE TABLE COCINERO;
TRUNCATE TABLE LIMPIEZA;
TRUNCATE TABLE LOCAL;
TRUNCATE TABLE ESTAR;
TRUNCATE TABLE RECETA;
TRUNCATE TABLE INGREDIENTE;
TRUNCATE TABLE PROVEEDOR;
TRUNCATE TABLE PAIS;

-- HABILITA LAS FOREIGN KEY'S
SET FOREIGN_KEY_CHECKS = 1;
