DROP DATABASE IF EXISTS CadenaRestauracion;

CREATE DATABASE CadenaRestauracion CHARACTER SET utf8mb4;
USE CadenaRestauracion;

CREATE TABLE PAIS (
    codigo_iso CHAR(2),
    nombre VARCHAR(64),
    moneda char(3), 
    poblacion INT,
    CONSTRAINT PK_PAIS PRIMARY KEY (codigo_iso)
);

CREATE TABLE PROVEEDOR (
    nif CHAR(9),
    nombre VARCHAR(128),
    CONSTRAINT PK_PROVEEDOR PRIMARY KEY (nif)
);

CREATE TABLE TELEFONO (
    numero VARCHAR(16),
    nifProveedor CHAR(9),
    CONSTRAINT PK_TELEFONO PRIMARY KEY (numero),
    CONSTRAINT FK_PROVEEDOR FOREIGN KEY (nifProveedor) REFERENCES PROVEEDOR(nif)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE PROVEER (
    nifProveedor CHAR(9),
    isoPais CHAR(2),
    CONSTRAINT PK_PROVEER PRIMARY KEY (nifProveedor, isoPais),
    CONSTRAINT FK_PROVEEDOR FOREIGN KEY (nifProveedor) REFERENCES PROVEEDOR(nif)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_PAIS FOREIGN KEY (isoPais) REFERENCES PAIS(codigo_iso)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE RECETA (
    id_receta INT UNSIGNED AUTO_INCREMENT,
    nombre VARCHAR(64),
    CONSTRAINT PK_RECETA PRIMARY KEY (id_receta)
);

CREATE TABLE INGREDIENTE (
    nombre VARCHAR(128),
    idReceta INT UNSIGNED,
    CONSTRAINT PK_INGREDIENTE PRIMARY KEY (nombre, idReceta),
    CONSTRAINT FK_INGREDIENTE FOREIGN KEY (idReceta) REFERENCES RECETA(id_receta)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE USAR (
    idReceta INT UNSIGNED,
    isoPais CHAR(2),
    CONSTRAINT PK_USAR PRIMARY KEY (idReceta, isoPais),
    CONSTRAINT FK_RECETA FOREIGN KEY (idReceta) REFERENCES RECETA(id_receta)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_PAIS FOREIGN KEY (isoPais) REFERENCES PAIS(codigo_iso)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE CLIENTE_FIDELIZADO (
    dni CHAR(9),
    nombre VARCHAR(128),
    fecha_nacimiento DATE,
    edad INT AS (TIMESTAMPDIFF(YEAR, fecha_nacimiento, CURDATE())) VIRTUAL,
    CONSTRAINT PK_CLIENTE_FIDELIZADO PRIMARY KEY(dni)
);

CREATE TABLE POSEER (
    dniCliente CHAR(9),
    isoPais CHAR(2),
    CONSTRAINT PK_POSEER PRIMARY KEY (dniCliente, isoPais),
    CONSTRAINT FK_dniCliente FOREIGN KEY (dniCliente) REFERENCES CLIENTE_FIDELIZADO(dni)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_PAIS FOREIGN KEY (isoPais) REFERENCES PAIS(codigo_iso)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE LOCAL ( 
    id_local INT UNSIGNED AUTO_INCREMENT,
    nombre VARCHAR(128),
    ciudad VARCHAR(64),
    calle VARCHAR(64),
    numero VARCHAR(8),
    codigo_postal CHAR(5),
    CONSTRAINT PK_LOCAL PRIMARY KEY (id_local)
);

CREATE TABLE ESTAR (
    idLocal INT UNSIGNED,
    isoPais CHAR(2),
    CONSTRAINT PK_ESTAR PRIMARY KEY (idLocal, isoPais),
    CONSTRAINT FK_LOCAL FOREIGN KEY (idLocal) REFERENCES LOCAL(id_local)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_PAIS FOREIGN KEY (isoPais) REFERENCES PAIS(codigo_iso)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE PEDIDO (
    numero_pedido INT UNSIGNED AUTO_INCREMENT,
    idLocal INT UNSIGNED,
    fecha DATETIME,
    nombre_cliente VARCHAR(128),
    dniCliente CHAR(9),
    total_precio DECIMAL(10,2),
    total_iva DECIMAL(10,2) AS (total_precio * 1.21) VIRTUAL,
    CONSTRAINT PK_PEDIDO PRIMARY KEY (numero_pedido, idLocal),
    CONSTRAINT FK_LOCAL FOREIGN KEY (idLocal) REFERENCES LOCAL(id_local)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_CLIENTE FOREIGN KEY (dniCliente) REFERENCES CLIENTE_FIDELIZADO(dni)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE TRABAJADOR (
    dni CHAR(9),
    nombre VARCHAR(128),
    dniCliente CHAR(9),
    CONSTRAINT PK_TRABAJADOR PRIMARY KEY (dni),
    CONSTRAINT FK_CLIENTE FOREIGN KEY (dniCliente) REFERENCES CLIENTE_FIDELIZADO(dni)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

CREATE TABLE TRABAJAR (
    idLocal INT UNSIGNED,
    dniTrabajador CHAR(9),
    CONSTRAINT PK_TRABAJAR PRIMARY KEY (idLocal, dniTrabajador),
    CONSTRAINT FK_LOCAL FOREIGN KEY (idLocal) REFERENCES LOCAL(id_local),
    CONSTRAINT FK_TRABAJADOR FOREIGN KEY (dniTrabajador) REFERENCES TRABAJADOR(dni)
);

CREATE TABLE LIMPIEZA (
    dniTrabajador CHAR(9),
    CONSTRAINT PK_TRABAJADOR PRIMARY KEY(dniTrabajador),
    CONSTRAINT FK_TRABAJADOR FOREIGN KEY(dniTrabajador) REFERENCES TRABAJADOR(dni)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE LIMPIAR(
    dniTrabajador CHAR(9),
    idLocal INT UNSIGNED,
    CONSTRAINT PK_LIMPIAR PRIMARY KEY (dniTrabajador, idLocal),
    CONSTRAINT FK_TRABAJADOR FOREIGN KEY (dniTrabajador) REFERENCES TRABAJADOR(dni)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_LOCAL FOREIGN KEY (idLocal) REFERENCES LOCAL(id_local)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE COCINERO (
    dniTrabajador CHAR(9),
    CONSTRAINT PK_TRABAJADOR PRIMARY KEY (dniTrabajador),
    CONSTRAINT FK_TRABAJADOR FOREIGN KEY (dniTrabajador) REFERENCES TRABAJADOR(dni)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE COCINAR (
    dniTrabajador CHAR(9),
    numPedido INT UNSIGNED,
    idLocal INT UNSIGNED,
    fecha DATETIME,
    CONSTRAINT PK_COCINAR PRIMARY KEY (dniTrabajador, idLocal, numPedido, fecha),
    CONSTRAINT FK_TRABAJADOR FOREIGN KEY (dniTrabajador) REFERENCES TRABAJADOR(dni)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_PEDIDO FOREIGN KEY (numPedido, idLocal) REFERENCES PEDIDO(numero_pedido, idLocal)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE CAJERO (
    dniTrabajador CHAR(9),
    CONSTRAINT PK_TRABAJADOR PRIMARY KEY (dniTrabajador),
    CONSTRAINT FK_TRABAJADOR FOREIGN KEY (dniTrabajador) REFERENCES TRABAJADOR(dni)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE ATENDER (
    dniTrabajador CHAR(9),
    numPedido INT UNSIGNED,
    idLocal INT UNSIGNED,
    fecha DATETIME,
    CONSTRAINT PK_ATENDER PRIMARY KEY (dniTrabajador, idLocal, numPedido, fecha),
    CONSTRAINT FK_TRABAJADOR FOREIGN KEY (dniTrabajador) REFERENCES TRABAJADOR(dni)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_PEDIDO FOREIGN KEY (numPedido, idLocal) REFERENCES PEDIDO(numero_pedido, idLocal)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE ENCARGADO (
    dniTrabajador CHAR(9),
    CONSTRAINT PK_TRABAJADOR PRIMARY KEY (dniTrabajador),
    CONSTRAINT FK_TRABAJADOR FOREIGN KEY (dniTrabajador) REFERENCES TRABAJADOR(dni)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE TRABAJO (
    idLocal INT UNSIGNED NOT NULL,
    dniTrabajador CHAR(9) NOT NULL,
    fecha DATETIME,
    CONSTRAINT PK_TRABAJO PRIMARY KEY (idLocal, dniTrabajador),
    CONSTRAINT FK_LOCAL FOREIGN KEY (idLocal) REFERENCES LOCAL(id_local)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_TRABAJADOR FOREIGN KEY (dniTrabajador) REFERENCES ENCARGADO(dniTrabajador)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE INCIDENCIA (
    id_incidencia INT UNSIGNED AUTO_INCREMENT,
    descripcion TEXT,
    CONSTRAINT PK_INCIDENCIA PRIMARY KEY (id_incidencia)
);

CREATE TABLE REGISTRAR (
    idLocal INT UNSIGNED,
    dniTrabajador CHAR(9),
    idIncidencia INT UNSIGNED,
    CONSTRAINT PK_REGISTRAR PRIMARY KEY (idLocal, dniTrabajador, idIncidencia),
    CONSTRAINT FK_INCIDENCIA FOREIGN KEY (idIncidencia) REFERENCES INCIDENCIA(id_incidencia)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_LOCAL FOREIGN KEY (idLocal) REFERENCES TRABAJO(idLocal)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_TRABAJADOR FOREIGN KEY (dniTrabajador) REFERENCES TRABAJO(dniTrabajador)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
