-- BORRA LA BASE DE DATOS SI EXISTE
DROP DATABASE IF EXISTS CadenaRestauracion;

-- CREA Y USA LA BASE DE DATOS CON UFT-8 PARA PERMITIR TODOS LOS CARÁCTERES
CREATE DATABASE CadenaRestauracion CHARACTER SET utf8mb4;
USE CadenaRestauracion;

-- CREA LA TABLA PAIS
CREATE TABLE PAIS (
    codigo_iso CHAR(2),
    nombre VARCHAR(64),
    moneda CHAR(3), 
    poblacion INT,
    CONSTRAINT PK_PAIS PRIMARY KEY (codigo_iso)
);

-- CREA LA TABLA PROVEEDOR
CREATE TABLE PROVEEDOR (
    nif CHAR(9),
    nombre VARCHAR(128),
    CONSTRAINT PK_PROVEEDOR PRIMARY KEY (nif)
);

-- CREA LA TABLA TELEFONO - ATRIBUTO MULTIEVALUADO DE PROVEEDOR
CREATE TABLE TELEFONO (
    numero VARCHAR(16),
    nifProveedor CHAR(9),
    CONSTRAINT PK_TELEFONO PRIMARY KEY (numero),
    CONSTRAINT FK_PROVEEDOR FOREIGN KEY (nifProveedor) REFERENCES PROVEEDOR(nif)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- CREA LA TABLA PROVEER - RELACIÓN ENTRE PAÍS Y PROVEEDOR
CREATE TABLE PROVEER (
    nifProveedor CHAR(9),
    isoPais CHAR(2),
    CONSTRAINT PK_PROVEER PRIMARY KEY (nifProveedor, isoPais),
    CONSTRAINT FK_PR_PROVEEDOR FOREIGN KEY (nifProveedor) REFERENCES PROVEEDOR(nif)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_PR_PAIS FOREIGN KEY (isoPais) REFERENCES PAIS(codigo_iso)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

-- CREA LA TABLA RECETA
CREATE TABLE RECETA (
    id_receta INT UNSIGNED AUTO_INCREMENT,
    nombre VARCHAR(64),
    CONSTRAINT PK_RECETA PRIMARY KEY (id_receta)
);

-- CREA LA TABLA INGREDIENTE - ATRIBUTO MULTIEVALUADO DE RECETA
CREATE TABLE INGREDIENTE (
    nombre VARCHAR(128),
    idReceta INT UNSIGNED,
    CONSTRAINT PK_INGREDIENTE PRIMARY KEY (nombre, idReceta),
    CONSTRAINT FK_INGREDIENTE FOREIGN KEY (idReceta) REFERENCES RECETA(id_receta)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- CREA LA TABLA USAR - RELACIÓN ENTRE PAÍS Y RECETA
CREATE TABLE USAR (
    idReceta INT UNSIGNED,
    isoPais CHAR(2),
    CONSTRAINT PK_USAR PRIMARY KEY (idReceta, isoPais),
    CONSTRAINT FK_USAR_RECETA FOREIGN KEY (idReceta) REFERENCES RECETA(id_receta)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_USAR_PAIS FOREIGN KEY (isoPais) REFERENCES PAIS(codigo_iso)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

-- CREA LA TABLA CLIENTE_FIDELIZADO
CREATE TABLE CLIENTE_FIDELIZADO (
    dni CHAR(9),
    nombre VARCHAR(128),
    fecha_nacimiento DATE,
    -- CREA UNA COLUMNA VIRTUAL - CALCULO OBTENIDO MEDIANTE (FECHA ACTUAL - FECHA_NACIMIENTO)
    edad INT AS (TIMESTAMPDIFF(YEAR, fecha_nacimiento, CURDATE())) VIRTUAL,
    CONSTRAINT PK_CLIENTE_FIDELIZADO PRIMARY KEY(dni)
);

-- CREA LA TABLA POSEER - RELACIÓN ENTRE PAÍS Y CLIENTE_FIDELIZADO
CREATE TABLE POSEER (
    dniCliente CHAR(9),
    isoPais CHAR(2),
    CONSTRAINT PK_POSEER PRIMARY KEY (dniCliente, isoPais),
    CONSTRAINT FK_PS_CLIENTE FOREIGN KEY (dniCliente) REFERENCES CLIENTE_FIDELIZADO(dni)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_PS_PAIS FOREIGN KEY (isoPais) REFERENCES PAIS(codigo_iso)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

-- CREA LA TABLA LOCAL
CREATE TABLE LOCAL ( 
    id_local INT UNSIGNED AUTO_INCREMENT,
    nombre VARCHAR(128),
    ciudad VARCHAR(64),
    calle VARCHAR(64),
    numero VARCHAR(8),
    codigo_postal CHAR(5),
    CONSTRAINT PK_LOCAL PRIMARY KEY (id_local)
);

-- CREA LA TABLA ESTAR - RELACIÓN ENTRE PAÍS Y LOCAL
CREATE TABLE ESTAR (
    idLocal INT UNSIGNED,
    isoPais CHAR(2),
    CONSTRAINT PK_ESTAR PRIMARY KEY (idLocal, isoPais),
    CONSTRAINT FK_ES_LOCAL FOREIGN KEY (idLocal) REFERENCES LOCAL(id_local)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_ES_PAIS FOREIGN KEY (isoPais) REFERENCES PAIS(codigo_iso)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

-- CREA LA TABLA PEDIDO - ENTIDAD DÉBIL DE LOCAL
CREATE TABLE PEDIDO (
    numero_pedido INT UNSIGNED AUTO_INCREMENT,
    idLocal INT UNSIGNED,
    fecha DATETIME,
    nombre_cliente VARCHAR(128),
    dniCliente CHAR(9),
    total_precio DECIMAL(10,2),
    -- CREA UNA COLUMNA VIRTUAL - CALCULO OBTENIDO MEDIANTE (TOTAL_PRECIO + IVA)
    total_iva DECIMAL(10,2) AS (total_precio * 1.21) VIRTUAL,
    CONSTRAINT PK_PEDIDO PRIMARY KEY (numero_pedido, idLocal),
    CONSTRAINT FK_PD_LOCAL FOREIGN KEY (idLocal) REFERENCES LOCAL(id_local)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_PD_CLIENTE FOREIGN KEY (dniCliente) REFERENCES CLIENTE_FIDELIZADO(dni)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

-- CREA LA TABLA TRABAJADOR - GENERALIZACIÓN DISJUNTIVA PARCIAL
CREATE TABLE TRABAJADOR (
    dni CHAR(9),
    nombre VARCHAR(128),
    dniCliente CHAR(9),
    CONSTRAINT PK_TRABAJADOR PRIMARY KEY (dni),
    CONSTRAINT FK_TR_CLIENTE FOREIGN KEY (dniCliente) REFERENCES CLIENTE_FIDELIZADO(dni)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

-- CREA LA TABLA TRABAJAR - RELACIÓN ENTRE LOCAL Y TRABAJADOR
CREATE TABLE TRABAJAR (
    idLocal INT UNSIGNED,
    dniTrabajador CHAR(9),
    CONSTRAINT PK_TRABAJAR PRIMARY KEY (idLocal, dniTrabajador),
    CONSTRAINT FK_TR_LOCAL FOREIGN KEY (idLocal) REFERENCES LOCAL(id_local),
    CONSTRAINT FK_TR_TRABAJADOR FOREIGN KEY (dniTrabajador) REFERENCES TRABAJADOR(dni)
);

-- CREA LA TABLA LIMPIEZA - SUBCLASE DE TRABAJADOR
CREATE TABLE LIMPIEZA (
    dniTrabajador CHAR(9),
    CONSTRAINT PK_LIM_TRABAJADOR PRIMARY KEY(dniTrabajador),
    CONSTRAINT FK_LIM_TRABAJADOR FOREIGN KEY(dniTrabajador) REFERENCES TRABAJADOR(dni)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- CREA LA TABLA LIMPIAR - RELACIÓN ENTRE LOCAL Y LIMPIEZA
CREATE TABLE LIMPIAR (
    dniTrabajador CHAR(9),
    idLocal INT UNSIGNED,
    CONSTRAINT PK_LIMPIAR PRIMARY KEY (dniTrabajador, idLocal),
    CONSTRAINT FK_LM_TRABAJADOR FOREIGN KEY (dniTrabajador) REFERENCES TRABAJADOR(dni)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_LM_LOCAL FOREIGN KEY (idLocal) REFERENCES LOCAL(id_local)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- CREA LA TABLA COCINERO - SUBCLASE DE TRABAJADOR
CREATE TABLE COCINERO (
    dniTrabajador CHAR(9),
    CONSTRAINT PK_CC_TRABAJADOR PRIMARY KEY (dniTrabajador),
    CONSTRAINT FK_CC_TRABAJADOR FOREIGN KEY (dniTrabajador) REFERENCES TRABAJADOR(dni)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- CREA LA TABLA COCINAR - RELACIÓN ENTRE PEDIDO Y COCINERO
CREATE TABLE COCINAR (
    dniTrabajador CHAR(9),
    numPedido INT UNSIGNED,
    idLocal INT UNSIGNED,
    fecha DATETIME,
    CONSTRAINT PK_COCINAR PRIMARY KEY (dniTrabajador, idLocal, numPedido, fecha),
    CONSTRAINT FK_CR_TRABAJADOR FOREIGN KEY (dniTrabajador) REFERENCES TRABAJADOR(dni)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_CR_PEDIDO FOREIGN KEY (numPedido, idLocal) REFERENCES PEDIDO(numero_pedido, idLocal)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- CREA LA TABLA CAJERO - SUBCLASE DE TRABAJADOR
CREATE TABLE CAJERO (
    dniTrabajador CHAR(9),
    CONSTRAINT PK_CJ_TRABAJADOR PRIMARY KEY (dniTrabajador),
    CONSTRAINT FK_CJ_TRABAJADOR FOREIGN KEY (dniTrabajador) REFERENCES TRABAJADOR(dni)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- CREA LA TABLA ATENDER - RELACIÓN ENTRE PEDIDO Y CAJERO
CREATE TABLE ATENDER (
    dniTrabajador CHAR(9),
    numPedido INT UNSIGNED,
    idLocal INT UNSIGNED,
    fecha DATETIME,
    CONSTRAINT PK_ATENDER PRIMARY KEY (dniTrabajador, idLocal, numPedido, fecha),
    CONSTRAINT FK_AT_TRABAJADOR FOREIGN KEY (dniTrabajador) REFERENCES TRABAJADOR(dni)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_AT_PEDIDO FOREIGN KEY (numPedido, idLocal) REFERENCES PEDIDO(numero_pedido, idLocal)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- CREA LA TABLA ENCARGADO - SUBCLASE DE TRABAJADOR
CREATE TABLE ENCARGADO (
    dniTrabajador CHAR(9),
    CONSTRAINT PK_EG_TRABAJADOR PRIMARY KEY (dniTrabajador),
    CONSTRAINT FK_EG_TRABAJADOR FOREIGN KEY (dniTrabajador) REFERENCES TRABAJADOR(dni)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- CREA LA TABLA TRABAJO - AGREGACIÓN ENTRE LOCAL, INCIDENCIA Y ENCARGADO
CREATE TABLE TRABAJO (
    idLocal INT UNSIGNED NOT NULL,
    dniTrabajador CHAR(9) NOT NULL,
    fecha DATETIME,
    CONSTRAINT PK_TRABAJO PRIMARY KEY (idLocal, dniTrabajador),
    CONSTRAINT FK_TRABAJO_LOCAL FOREIGN KEY (idLocal) REFERENCES LOCAL(id_local)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_TRABAJO_TRABAJADOR FOREIGN KEY (dniTrabajador) REFERENCES ENCARGADO(dniTrabajador)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- CREA LA TABLA INCIDENCIA - ENTIDAD DE LA AGREGACIÓN TRABAJO
CREATE TABLE INCIDENCIA (
    id_incidencia INT UNSIGNED AUTO_INCREMENT,
    descripcion TEXT,
    CONSTRAINT PK_INCIDENCIA PRIMARY KEY (id_incidencia)
);

-- CREA LA TABLA REGISTRAR - RELACIÓN ENTRE TRABAJO E INCIDENCIA
CREATE TABLE REGISTRAR (
    idLocal INT UNSIGNED,
    dniTrabajador CHAR(9),
    idIncidencia INT UNSIGNED,
    CONSTRAINT PK_REGISTRAR PRIMARY KEY (idLocal, dniTrabajador, idIncidencia),
    CONSTRAINT FK_RG_INCIDENCIA FOREIGN KEY (idIncidencia) REFERENCES INCIDENCIA(id_incidencia)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_RG_LOCAL FOREIGN KEY (idLocal) REFERENCES TRABAJO(idLocal)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_RG_TRABAJADOR FOREIGN KEY (dniTrabajador) REFERENCES TRABAJO(dniTrabajador)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
