/*Desactiva temporalmente las claves foráneas para que así no de ningún error al vaciar las tablas*/
SET FOREIGN_KEY_CHECKS = 0;

-- Vaciar todas las tablas
TRUNCATE TABLE INGREDIENTES;
TRUNCATE TABLE REGISTRAR;
TRUNCATE TABLE INCIDENCIA;
TRUNCATE TABLE TRABAJO;
TRUNCATE TABLE ENCARGADO;
TRUNCATE TABLE LIMPIAR;
TRUNCATE TABLE LIMPIEZA;
TRUNCATE TABLE TRABAJADOR;
TRUNCATE TABLE PEDIDO;
TRUNCATE TABLE ESTAR;
TRUNCATE TABLE LOCAAL;
TRUNCATE TABLE POSEER;
TRUNCATE TABLE CLIENTE_FIDELIZADO;
TRUNCATE TABLE USAR;
TRUNCATE TABLE RECETA;
TRUNCATE TABLE PROVEER;
TRUNCATE TABLE TELEFONO;
TRUNCATE TABLE PROVEEDOR;
TRUNCATE TABLE PAIS;

/*Las vuelve a activar para poder insertar datos de nuevo*/
SET FOREIGN_KEY_CHECKS = 1;
